service:
  port: 80
  name: "1239"

mysql:
  username: "root"
  password: "admin123"
  database: "talk"
  url: "127.0.0.1"

redis:
  addr: "47.113.189.23:6379"
  db: 0
  password: "admin123"
  poolsize: 1000
  maxidleconns: 1000
  minidleconns: 10
  connMaxIdleTime: 10


jwt:
  time: 12
  key: "welcome to use Tally by Mr.Lei"

